version: '3'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    container_name: 'jenkins'
    user: root
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./home:/home
    ports:
      - 8080:8080
